// lib/versioning.ts
// Simple helper to expose data version information for the Trust & Methodology panel.
// It reads a JSON file (summaries/metadata.json) that should be generated by the data pipeline.
// If the file is missing, we fall back to a static placeholder.

import path from 'path';

export interface VersionInfo {
  dataVersion: string;
  commitHash?: string;
  generatedAt: string;
}

/**
 * Load version metadata from the JSON file using fetch (client‑side).
 */
export async function getVersionInfo(): Promise<VersionInfo> {
  const metadataUrl = '/summaries/metadata.json';
  try {
    const res = await fetch(metadataUrl);
    const parsed = await res.json();
    return {
      dataVersion: parsed.dataVersion ?? 'unknown',
      commitHash: parsed.commitHash,
      generatedAt: parsed.generatedAt ?? new Date().toISOString(),
    } as VersionInfo;
  } catch {
    return {
      dataVersion: 'unknown',
      generatedAt: new Date().toISOString(),
    };
  }
}
